name: thesis
channels:
  - defaults
dependencies:
  - python=3.13.2
  - numpy
  - tqdm
  - pip
  - pip:
    # tell pip where to find the CUDA 12.8 wheels
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - jupyterlab
    - torch==2.7.0
    - torchaudio==2.7.0
    - torchvision==0.22.0
    - egnn_pytorch
    - mdtraj
    - optuna